# Generated by Django 5.1 on 2024-10-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coupon_shippingadress_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='api.variant'),
        ),
    ]
